language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install texinfo curl openssl libxml2

before_script:
    - ./travis/compile-php.sh
    - ./travis/compile-libjit.sh
    - ./travis/compile-ext.sh

script:
    - ./travis/run-tests.sh
    - ./travis/run-recki-tests.sh

